// <auto-generated />
using System;
using Mesher.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mesher.Database.Migrations
{
    [DbContext(typeof(MesherContext))]
    [Migration("20251120173238_MeshMessagesIndex")]
    partial class MeshMessagesIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mesher.Database.DbMeshHardware", b =>
                {
                    b.Property<int>("Key")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("character varying(8192)");

                    b.HasKey("Key");

                    b.ToTable("MeshHardwares");
                });

            modelBuilder.Entity("Mesher.Database.DbMeshMessage", b =>
                {
                    b.Property<Guid>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("Channel")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasComputedColumnSql("(CAST(\"RawMessage\" ->> 'channel' AS bigint))", true);

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("From")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasComputedColumnSql("(CAST(\"RawMessage\" ->> 'from' AS bigint))", true);

                    b.Property<double>("RSSI")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("double precision")
                        .HasComputedColumnSql("(CAST(\"RawMessage\" ->> 'rssi' AS double precision))", true);

                    b.Property<string>("RawMessage")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("jsonb");

                    b.Property<double>("SNR")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("double precision")
                        .HasComputedColumnSql("(CAST(\"RawMessage\" ->> 'snr' AS double precision))", true);

                    b.Property<long>("To")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasComputedColumnSql("(CAST(\"RawMessage\" ->> 'to' AS bigint))", true);

                    b.Property<string>("Type")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasComputedColumnSql("(CAST(\"RawMessage\" ->> 'type' AS text))", true);

                    b.HasKey("EntryId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_MeshMessages_CreatedAt_DESC")
                        .HasAnnotation("Npgsql:IndexSortOrder", new[] { SortOrder.Descending });

                    b.HasIndex("From")
                        .HasDatabaseName("IX_MeshMessages_From");

                    b.HasIndex("To")
                        .HasDatabaseName("IX_MeshMessages_To");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_MeshMessages_Type");

                    b.ToTable("MeshMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
